### ISSUE TITLE
error during installation: could not find function "guides"

### ISSUE THREAD

**Issue by hopjesvla79** [cbielow/PTXQC#12]
Hi,
trying to intsall PTXQC as a noob, i try the Drag 'n Drop method. Following all the instructiosn i'm stuck at the following error:

"Quitting from lines 33-60 (PTXQC-Basic_Guide_for_R_users.Rmd) 
Error: processing vignette 'PTXQC-Basic_Guide_for_R_users.Rmd' failed with diagnostics:
could not find function "guides"
Execution halted
Error: Command failed (1)"

what is going wrong?

**Comment by cbielow** [comment]
I've never seen this error, but it looks like a problem with ggplot2 or your R version. See [1].
So, maybe updating R and/or ggplot2 already solves the issue.

What is R version, i.e ```R.Version()```?

  [1] [http://stackoverflow.com/questions/22072354/error-could-not-find-function-guides]

**Comment by hopjesvla79** [comment]
Hi,
it seems that updating ggplot 2 was indeed necessary, at least now it's working. 

Thanks!

**Comment by cbielow** [comment]
Sweet.
Merry X-Mas!
