### ISSUE TITLE
Contaminant recognition

### ISSUE THREAD

**Issue by ofleitas** [cbielow/PTXQC#127]
Hello 
I am analyzing my proteomic data with Maxquant, but I am no using the Maxquant contaminant FASTA files instead I am using the contaminant FASTA file reported by Frankenfield et al., 2022 (Ashley M. Frankenfield, Jiawei Ni, Mustafa Ahmed, and Ling Hao Journal of Proteome Research 2022 21 (9), 2104-2113,DOI: 10.1021/acs.jproteome.2c00145).  The contaminant FASTA file reported by Frankenfield et al., 2022 is more updated than Maxquant contaminant FASTA file and cRAP. When the contaminant FASTA file reported by Frankenfield et al., 2022 is integrated in MaxQuant, the identified contaminants will appear in column Protein ID with the prefix ‘Cont_’ and not in the column Potential contaminant(proteinGroups.txt). Then when I run PTXQC, it is not recognized the presence of contaminants. Appear the follows message: “No contaminants found in any sample.  Incorporating contaminants during search is highly recommended! “
Then I think that could be great adapt PTXQC to recognize in the MaxQuant output the contaminants reported by Frankenfield et al., 2022. 
Best regards

**Comment by cbielow** [comment]
thanks for reporting.
So, just to make sure I understand correctly:
you disabled `Include Contaminants` in MaxQuant and added a custom FASTA file in MaxQuant (along with the FASTA file for the actual species you are interested in)?

Alternative solution: you can replace the `MaxQuant_1.2.3\bin\conf\contaminants.fasta` with the Frankenfield FASTA (and keep `Include Contaminants` in MaxQuant to "on"). Then MaxQuant will use your contaminant DB and the `Potential Contaminant` column should be correctly populated by MaxQuant.
This way, no change to PTXQC is required.

**Comment by ofleitas** [comment]
Dear Chris

Your solution worked well. Thank you very much for your help.
Best regards
