### ISSUE TITLE
qualUniform(x$ratio, x$count)

### ISSUE THREAD

**Issue by mthang** [cbielow/PTXQC#129]
Hi there,
My Maxquant run keeps running into this issue and I am not an export of the PTXQC nor the python scripts. Briefly, the error message below was generated from the Maxquant run on the Galaxy. I had a few success run before this failed job, and I am not sure what's going on. 

Loading package PTXQC (version 1.0.10) 
Warning message: In readLines(con, warn = readLines.warn) :   
incomplete final line found on '/mnt/pulsar/files/staging/6083917/configs/tmprfy3xjnf' 
Coordinate system already present. Adding new coordinate system, which will replace the existing one. 
Coordinate system already present. Adding new coordinate system, which will replace the existing one. 
Worker of 'EVD:User~Contaminant~(%s)' returned prematurely due to missing data! Skipping metric! 
Coordinate system already present. Adding new coordinate system, which will replace the existing one. 
Info: Two reporter.intensity and two reporter.intensity.corrected columns are needed for metric ReporterIntensity. 
Worker of 'EVD:~Reporter~intensity' returned prematurely due to missing data! Skipping metric! 
Warning in workerFcn(.self, df, ...) :   Cannot find a unique reference Raw file (files: Emma_M1904_145.raw.thermo).
 Picking the first. Error in qualUniform(x$ratio, x$count) :    Error: qualUniform() received negative or missing data! 
Calls: createReport ... loop_apply -> <Anonymous> -> .fun -> data.frame -> qualUniform 
In addition: Warning messages: 
1: Vectorized input to `element_text()` is not officially supported. ℹ Results may be unexpected or may change in future versions of ggplot2.  
2: The `<scale>` argument of `guides()` cannot be `FALSE`. Use "none" instead as of ggplot2 3.3.4. ℹ The deprecated feature was likely used in the PTXQC package.   Please report the issue at <https://github.com/cbielow/PTXQC/issues>.  Execution halted

**Comment by cbielow** [comment]
Hi,

thanks for reporting this!
Could you upload the txt folder somewhere and provide a download link here? Then I can take a look whats going wrong.

Alternatively, you can try to process your data with the online-version of PTXQC at ptxqc.bsc.fu-berlin.de, since your PTXQC version is a bit older (and the bug may be fixed in a more recent version).

**Comment by cbielow** [comment]
Has this problem been solved?
I will close the ticket, please reopen or simply reply if needed.
