### ISSUE TITLE
vignette building fails during installation

### ISSUE THREAD

**Issue by satzel** [cbielow/PTXQC#15]
Hi Chris,

I managed to install PTXQC without any problems on my Mac and could create a QC report by connecting to the corresponding txt folder on the network drive, all good.
But when I try to install it on a Windows machine, the install_github command fails.
Here ist what I get and my session info:

> install_github("cbielow/PTXQC", build_vignettes = TRUE) 
Downloading GitHub repo cbielow/PTXQC@master
Installing PTXQC
"C:/PROGRA~1/R/R-32~1.3/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore CMD build  \
  "C:\Users\sas\AppData\Local\Temp\RtmpcJf0s1\devtoolsfb0406e3de6\cbielow-PTXQC-96df116"  \
  --no-resave-data --no-manual 

* checking for file 'C:\Users\sasrei\AppData\Local\Temp\RtmpcJf0s1\devtoolsfb0406e3de6\cbielow-PTXQC-96df116/DESCRIPTION' ... OK
* preparing 'PTXQC':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ...Warning: running command '"C:/PROGRA~1/R/R-32~1.3/bin/x64/Rscript" --vanilla --default-packages= -e "tools::buildVignettes(dir = '.', tangle = TRUE)"' had status 1
 ERROR
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  Pandoc (>= 1.12.3) and/or pandoc-citeproc is not available. Please install both.
Warning in readLines(con) :
  incomplete final line found on 'PTXQC-Basic_Guide_for_R_users.Rmd'
Error: processing vignette 'PTXQC-Basic_Guide_for_R_users.Rmd' failed with diagnostics:
It seems you should call rmarkdown::render() instead of knitr::knit2html() because PTXQC-Basic_Guide_for_R_users.Rmd appears to be an R Markdown v2 document.
Execution halted
Error: Command failed (1)

> session_info()
Session info -----------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.3 (2015-12-10)
 system   x86_64, mingw32             
 ui       Rgui                        
 language (EN)                        
 collate  English_Australia.1252      
 tz       Australia/Sydney            
 date     2016-01-18                  

Packages ---------------------------------------------------------------------------------------------------------
 package       * version date       source        
 Biobase       * 2.30.0  2015-10-14 Bioconductor  
 BiocGenerics  * 0.16.1  2015-11-06 Bioconductor  
 BiocInstaller   1.20.1  2015-11-18 Bioconductor  
 curl            0.9.4   2015-11-20 CRAN (R 3.2.3)
 devtools      * 1.9.1   2015-09-11 CRAN (R 3.2.3)
 digest          0.6.9   2016-01-08 CRAN (R 3.2.3)
 httr            1.0.0   2015-06-25 CRAN (R 3.2.3)
 knitr           1.12    2016-01-07 CRAN (R 3.2.3)
 magrittr        1.5     2014-11-22 CRAN (R 3.2.3)
 memoise         0.2.1   2014-04-22 CRAN (R 3.2.3)
 R6              2.1.1   2015-08-19 CRAN (R 3.2.3)
 stringi         1.0-1   2015-10-22 CRAN (R 3.2.3)
 stringr         1.0.0   2015-04-30 CRAN (R 3.2.3)

I tried installing pandoc but got the same error afterwards.
Any hints? 

Thanks a lot
cheers
satz

**Comment by cbielow** [comment]
Ok, looks like a third-party package problem.
According to http://stackoverflow.com/questions/24861970/using-rmarkdown-as-a-vignette-engine,
rmarkdown needs to be present when building markdownV2.

So, could you try installing rmarkdown and the run install_github again?
If that fixes it, I'll figure out how to make rmarkdown a hard dependency :)

**Comment by cbielow** [comment]
ha, I just realize rmarkdown is already a dependency, but it does not show up in your list of packages.
Did it get installed correctly?

**Comment by satzel** [comment]
Thanks Chris, I checked now if knitr and markdown are installed and loaded them and tried the installation again and it all worked out. I don't know what was wrong but all good now and thanks for your immediate reply.
cheers :)

**Comment by cbielow** [comment]
I followed this up because other users seem have the same problem.

The reason why R still failed even after installing Pandoc is simply that you need to restart R. Only then will R find Pandoc.

I updated the installation instructions accordingly.
