### ISSUE TITLE
PTXQC installing failure

### ISSUE THREAD

**Issue by ParisWu** [cbielow/PTXQC#16]
Hi, I am a PTXQC user from China, there is some problem in installing PTXQC in my laptop.

The R version is 3.2.3

The command is as follows:

> if (!require(devtools, quietly = TRUE)) install.packages("devtools")
> library("devtools")  
> source("http://bioconductor.org/biocLite.R")
Bioconductor version 3.2 (BiocInstaller 1.20.1), ?biocLite for help
> biocLite("Biobase")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.2 (BiocInstaller 1.20.1), R 3.2.3 (2015-12-10).
Installing package(s) ‘Biobase’
试开URL’https://bioconductor.org/packages/3.2/bioc/bin/windows/contrib/3.2/Biobase_2.30.0.zip'
Content type 'application/zip' length 4227858 bytes (4.0 MB)
downloaded 4.0 MB

package ‘Biobase’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\Administrator\AppData\Local\Temp\Rtmpe8h2Nd\downloaded_packages
> install_github("cbielow/PTXQC", build_vignettes = TRUE)
Downloading GitHub repo cbielow/PTXQC@master
Installing PTXQC
"C:/Program Files/R/R-32~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD build  \
  "C:\Users\Administrator\AppData\Local\Temp\Rtmpe8h2Nd\devtoolsf081956398e\cbielow-PTXQC-96df116" --no-resave-data  \
  --no-manual

**Comment by cbielow** [comment]
The log you posted looks fine to me.

What is the error you see (i.e. what is you question) :) ?

Sometimes the R console does not output any progress for quite some time -- usually then the CRAN/BC servers are unreachable or under high load. Usually, the problem is solved by waiting and trying again.

**Comment by ParisWu** [comment]
Thanks for replying me, myproblem is I can not find PTXQC package in my R library, just as follows：
 > help(package="PTXQC")
starting httpd help server ... done。
> browseVignettes(package="PTXQC")
Error in find.package(package, lib.loc) : 
  there is no package called ‘PTXQC’

**Comment by cbielow** [comment]
did you follow the drag'n'drop installation procedure, i.e. if you used

```
##
## the following section of code is only required to create a self-contained 
## library folder which hosts all required packages for PTXQC for ease of copying
##
tmp_dir = tempfile("PTXQC_pck_")
dir.create(tmp_dir)
.libPaths(tmp_dir)
cat(paste0("\nNew temporary library folder: '", .libPaths()[1], "' created. Installing PTXQC ...\n"))
```

before using the commands you posted initially, then PTXQC was installed to a temporary library.
If you restart R, this temp-library will be lost and R cannot find PTXQC.

Please re-read the installation manual carefully! If you want PTXQC for interactive usage in your local R installation, you must not use the first code block (which I posted here). Further details in the manual.

**Comment by ParisWu** [comment]
Hi, I follow the installing step as follows:

"If you just want the package to use (and maybe even modify) it:

The following lines will install the PTXQC package. Direct installation from GitHub requires the 'devtools' package. Run each line separately in your R console, i.e. do not copy and paste the whole block. If an error should occur, this allows to track it down more easily. See FAQ - Installation how to resolve them.

if (!require(devtools, quietly = TRUE)) install.packages("devtools")
library("devtools")             ## this might give a warning like 'WARNING: Rtools is required ...'. Ignore it.
source("http://bioconductor.org/biocLite.R")
biocLite("Biobase")
install_github("cbielow/PTXQC", build_vignettes = TRUE) 
If you just want the package to use (and maybe even modify) it:

The following lines will install the PTXQC package. Direct installation from GitHub requires the 'devtools' package. Run each line separately in your R console, i.e. do not copy and paste the whole block. If an error should occur, this allows to track it down more easily. See FAQ - Installation how to resolve them.

if (!require(devtools, quietly = TRUE)) install.packages("devtools")
library("devtools")             ## this might give a warning like 'WARNING: Rtools is required ...'. Ignore it.
source("http://bioconductor.org/biocLite.R")
biocLite("Biobase")
install_github("cbielow/PTXQC", build_vignettes = TRUE) "

and in my R running:

" 
> if (!require(devtools, quietly = TRUE)) install.packages("devtools")
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools 3.3 from http://cran.r-project.org/bin/windows/Rtools/ and then run find_rtools().
> library("devtools") 
> source("http://bioconductor.org/biocLite.R")
Bioconductor version 3.2 (BiocInstaller 1.20.1), ?biocLite for help
> biocLite("Biobase")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.2 (BiocInstaller 1.20.1), R 3.2.3 (2015-12-10).
Installing package(s) ‘Biobase’
试开URL’https://bioconductor.org/packages/3.2/bioc/bin/windows/contrib/3.2/Biobase_2.30.0.zip'
Content type 'application/zip' length 4227858 bytes (4.0 MB)
downloaded 4.0 MB

package ‘Biobase’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\Administrator\AppData\Local\Temp\RtmpUV2fhL\downloaded_packages
Old packages: 'nlme'
Update all/some/none? [a/s/n]: A

  有二进制版本的，但源代码版本是后来的:
      binary  source needs_compilation
nlme 3.1-123 3.1-124              TRUE

  Binaries will be installed
试开URL’https://cran.rstudio.com/bin/windows/contrib/3.2/nlme_3.1-123.zip'
Content type 'application/zip' length 2149286 bytes (2.0 MB)
downloaded 2.0 MB

package ‘nlme’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\Administrator\AppData\Local\Temp\RtmpUV2fhL\downloaded_packages
> install_github("cbielow/PTXQC", build_vignettes = TRUE)
Downloading GitHub repo cbielow/PTXQC@master
Installing PTXQC
"C:/Program Files/R/R-32~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD build  \
  "C:\Users\Administrator\AppData\Local\Temp\RtmpUV2fhL\devtools109045ef7861\cbielow-PTXQC-6322c99" --no-resave-data --no-manual 

'C:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
错误: Command failed (1)"
 so, I can not find what is wrong in my installation process.
Thanks very much !
