### ISSUE TITLE
installation fail

### ISSUE THREAD

**Issue by ParisWu** [cbielow/PTXQC#17]
Hi, me again, when install the PTXQC in my desktop, I have a probelm, which induced command failed. The error said: " It seems you should call rmarkdown::render() instead of knitr::knit2html() because PTXQC-Basic_Guide_for_R_users.Rmd appears to be an R Markdown v2 document."
my R version is R-3.2,3 (64 bit). Please help me! Thanks!

the installation command as follows:

> if (!require(devtools, quietly = TRUE)) install.packages("devtools")
> library("devtools")
> source("http://bioconductor.org/biocLite.R")
Bioconductor version 3.2 (BiocInstaller 1.20.1), ?biocLite for help
> biocLite("Biobase")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.2 (BiocInstaller 1.20.1), R 3.2.3 (2015-12-10).
Installing package(s) ‘Biobase’
试开URL’https://bioconductor.org/packages/3.2/bioc/bin/windows/contrib/3.2/Biobase_2.30.0.zip'
Content type 'application/zip' length 4227858 bytes (4.0 MB)
downloaded 4.0 MB

package ‘Biobase’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\Administrator\AppData\Local\Temp\RtmpkvLked\downloaded_packages
Old packages: 'nlme'
Update all/some/none? [a/s/n]: a

  有二进制版本的，但源代码版本是后来的:
      binary  source needs_compilation
nlme 3.1-123 3.1-124              TRUE

  Binaries will be installed
试开URL’https://cran.rstudio.com/bin/windows/contrib/3.2/nlme_3.1-123.zip'
Content type 'application/zip' length 2149286 bytes (2.0 MB)
downloaded 2.0 MB

package ‘nlme’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\Administrator\AppData\Local\Temp\RtmpkvLked\downloaded_packages
> install_github("cbielow/PTXQC", build_vignettes = TRUE)
Downloading GitHub repo cbielow/PTXQC@master
Installing PTXQC
"D:/R/R-3.2.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD build  \
  "C:\Users\Administrator\AppData\Local\Temp\RtmpkvLked\devtools74441935eae\cbielow-PTXQC-6322c99" --no-resave-data --no-manual 

* checking for file 'C:\Users\Administrator\AppData\Local\Temp\RtmpkvLked\devtools74441935eae\cbielow-PTXQC-6322c99/DESCRIPTION' ... OK
* preparing 'PTXQC':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ...Warning: 运行命令'"D:/R/R-32~1.3/bin/x64/Rscript" --vanilla --default-packages= -e "tools::buildVignettes(dir = '.', tangle = TRUE)"'的状态是1
 ERROR
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  Pandoc (>= 1.12.3) and/or pandoc-citeproc is not available. Please install both.
错误: 处理标头'PTXQC-Basic_Guide_for_R_users.Rmd'失败，诊断信息为:
It seems you should call rmarkdown::render() instead of knitr::knit2html() because PTXQC-Basic_Guide_for_R_users.Rmd appears to be an R Markdown v2 document.
停止执行
错误: Command failed (1)

**Comment by cbielow** [comment]
Thanks for reporting this. It's the second report of this kind (see #15 for instructions how to fix it).
i.e.

```
library(rmarkdown)
library(knitr)
```

and then re-run `install_github(......)` again as you did before.

Does that work?

(If it works, I'll file a bugreport with the devtools package, since it seems they broke some dependency).

**Comment by ParisWu** [comment]
it does not work out!!!!!!
I wonder if I use the lastest R version or not? (R 3.2.3) 


> library(rmarkdown)
> library(knitr)
> install_github("cbielow/PTXQC", build_vignettes = TRUE) 
Downloading GitHub repo cbielow/PTXQC@master
Installing PTXQC
"E:/Ping/R-3.2.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD build "C:\Users\waters\AppData\Local\Temp\RtmpsbdrfH\devtools1eb84351a3f27\cbielow-PTXQC-6322c99" --no-resave-data --no-manual 

* checking for file 'C:\Users\waters\AppData\Local\Temp\RtmpsbdrfH\devtools1eb84351a3f27\cbielow-PTXQC-6322c99/DESCRIPTION' ... OK
* preparing 'PTXQC':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ...Warning: 运行命令'"E:/Ping/R-32~1.3/bin/x64/Rscript" --vanilla --default-packages= -e "tools::buildVignettes(dir = '.', tangle = TRUE)"'的状态是1
 ERROR
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  Pandoc (>= 1.12.3) and/or pandoc-citeproc is not available. Please install both.
错误: 处理标头'PTXQC-Basic_Guide_for_R_users.Rmd'失败，诊断信息为:
It seems you should call rmarkdown::render() instead of knitr::knit2html() because PTXQC-Basic_Guide_for_R_users.Rmd appears to be an R Markdown v2 document.
停止执行
错误: Command failed (1)

**Comment by cbielow** [comment]
The bug is found and fixed. Thanks for reporting it.
See the updated installation instructions for details.

In short you can either:
a) disable vignette building, i.e. `install_github("cbielow/PTXQC", build_vignettes = FALSE)`

b) install pandoc (see installation instructions), if you need the vignettes
