### ISSUE TITLE
Error : cannot allocate vector of size 125.0 Mb

### ISSUE THREAD

**Issue by ParisWu** [cbielow/PTXQC#19]
Hi Chris,
       I have encountered an error just as tile say, in this case, I have 206 sample in together to analyze, how to configure it out? Thanks!
 R version 3.2.3 (2015-12-10), windows 7 system, 64 bit

> require(PTXQC)
Loading required package: PTXQC
Loading package PTXQC (version 0.80.0)
> txt_folder = "D:/R/mydirectory/PTXQC/shenhuahao-103/txt"
> r = createReport(txt_folder)
getYAML with: PTXQC$UseLocalMQPar  default: TRUE 
 .. return default: TRUE 
getYAML with: PTXQC$ReportFilename$extended  default: TRUE 
 .. return default: TRUE 
meta id:  qcMetric_PAR 
getYAML with: order$qcMetric_PAR  default: 1 
 .. return default: 1 
meta id:  qcMetric_PG_PCA 
getYAML with: order$qcMetric_PG_PCA  default: 3 
 .. return default: 3 
meta id:  qcMetric_EVD_Top5Cont 
getYAML with: order$qcMetric_EVD_Top5Cont  default: 10 
 .. return default: 10 
meta id:  qcMetric_PG_Ratio 
getYAML with: order$qcMetric_PG_Ratio  default: 19 
 .. return default: 19 
meta id:  qcMetric_EVD_UserContaminant 
getYAML with: order$qcMetric_EVD_UserContaminant  default: 20 
 .. return default: 20 
meta id:  qcMetric_EVD_PeptideInt 
getYAML with: order$qcMetric_EVD_PeptideInt  default: 30 
 .. return default: 30 
meta id:  qcMetric_PG_RawInt 
getYAML with: order$qcMetric_PG_RawInt  default: 32 
 .. return default: 32 
meta id:  qcMetric_PG_LFQInt 
getYAML with: order$qcMetric_PG_LFQInt  default: 33 
 .. return default: 33 
meta id:  qcMetric_PG_ITRAQInt 
getYAML with: order$qcMetric_PG_ITRAQInt  default: 34 
 .. return default: 34 
meta id:  qcMetric_MSMS_MissedCleavages 
getYAML with: order$qcMetric_MSMS_MissedCleavages  default: 40 
 .. return default: 40 
meta id:  qcMetric_EVD_Charge 
getYAML with: order$qcMetric_EVD_Charge  default: 100 
 .. return default: 100 
meta id:  qcMetric_PG_Cont 
getYAML with: order$qcMetric_PG_Cont  default: 110 
 .. return default: 110 
meta id:  qcMetric_MSMSScans_TopNoverRT 
getYAML with: order$qcMetric_MSMSScans_TopNoverRT  default: 120 
 .. return default: 120 
meta id:  qcMetric_EVD_IDoverRT 
getYAML with: order$qcMetric_EVD_IDoverRT  default: 150 
 .. return default: 150 
meta id:  qcMetric_EVD_RTPeakWidth 
getYAML with: order$qcMetric_EVD_RTPeakWidth  default: 170 
 .. return default: 170 
meta id:  qcMetric_EVD_MBRAlign 
getYAML with: order$qcMetric_EVD_MBRAlign  default: 210 
 .. return default: 210 
meta id:  qcMetric_EVD_MBRIdTransfer 
getYAML with: order$qcMetric_EVD_MBRIdTransfer  default: 220 
 .. return default: 220 
meta id:  qcMetric_EVD_MBRaux 
getYAML with: order$qcMetric_EVD_MBRaux  default: 221 
 .. return default: 221 
meta id:  qcMetric_MSMSScans_IonInjTime 
getYAML with: order$qcMetric_MSMSScans_IonInjTime  default: 240 
 .. return default: 240 
meta id:  qcMetric_EVD_MS2OverSampling 
getYAML with: order$qcMetric_EVD_MS2OverSampling  default: 250 
 .. return default: 250 
meta id:  qcMetric_EVD_PreCal 
getYAML with: order$qcMetric_EVD_PreCal  default: 260 
 .. return default: 260 
meta id:  qcMetric_EVD_PostCal 
getYAML with: order$qcMetric_EVD_PostCal  default: 270 
 .. return default: 270 
meta id:  qcMetric_MSMS_MSMSDecal 
getYAML with: order$qcMetric_MSMS_MSMSDecal  default: 280 
 .. return default: 280 
meta id:  qcMetric_SM_MSMSIdRate 
getYAML with: order$qcMetric_SM_MSMSIdRate  default: 300 
 .. return default: 300 
meta id:  qcMetric_MSMSScans_TopN 
getYAML with: order$qcMetric_MSMSScans_TopN  default: 350 
 .. return val: 120 
meta id:  qcMetric_MSMSScans_TopNID 
getYAML with: order$qcMetric_MSMSScans_TopNID  default: 380 
 .. return default: 380 
meta id:  qcMetric_EVD_PeptideCount 
getYAML with: order$qcMetric_EVD_PeptideCount  default: 400 
 .. return default: 400 
meta id:  qcMetric_EVD_ProteinCount 
getYAML with: order$qcMetric_EVD_ProteinCount  default: 450 
 .. return default: 450 
meta id:  qcMetric_AverageQualOverall 
getYAML with: order$qcMetric_AverageQualOverall  default: 9999 
 .. return default: 9999 
getYAML with: File$Parameters$enabled  default: TRUE 
 .. return default: TRUE 
Reading file D:/R/mydirectory/PTXQC/shenhuahao-103/txt/parameters.txt ...
Read 61 entries from D:/R/mydirectory/PTXQC/shenhuahao-103/txt/parameters.txt.
Updating colnames
Simplifying contaminants
Simplifying reverse
Starting to work on PAR: MQ Parameters ...
... PAR: MQ Parameters  done
getYAML with: PTXQC$NameLengthMax_num  default: 10 
 .. return default: 10 
getYAML with: File$Summary$enabled  default: TRUE 
 .. return default: TRUE 
Reading file D:/R/mydirectory/PTXQC/shenhuahao-103/txt/summary.txt ...
Read 413 entries from D:/R/mydirectory/PTXQC/shenhuahao-103/txt/summary.txt.
Updating colnames
Simplifying contaminants
Simplifying reverse
Adding fc.raw.file column ... done
getYAML with: File$Summary$IDRate$Thresh_bad_num  default: 20 
 .. return default: 20 
getYAML with: File$Summary$IDRate$Thresh_great_num  default: 35 
 .. return default: 35 
Starting to work on SM: MS^2 ID rate (">%1.0f") ...
... SM: MS^2 ID rate (">%1.0f")  done
getYAML with: File$ProteinGroups$enabled  default: TRUE 
 .. return default: TRUE 
getYAML with: File$ProteinGroups$RatioPlot$LabelIncThresh_num  default: 4 
 .. return default: 4 
Reading file D:/R/mydirectory/PTXQC/shenhuahao-103/txt/proteinGroups.txt ...
Read 1287 entries from D:/R/mydirectory/PTXQC/shenhuahao-103/txt/proteinGroups.txt.
Updating colnames
Simplifying contaminants
Simplifying reverse
getYAML with: File$ProteinGroups$IntensityThreshLog2_num  default: 25 
 .. return default: 25 
Starting to work on PG: Contaminants ...
... PG: Contaminants  done
Starting to work on PG: raw intensity ...
... PG: raw intensity  done
Starting to work on PG: LFQ intensity ...
... PG: LFQ intensity  done
Starting to work on PG: Principal Component ...
... PG: Principal Component  done
getYAML with: File$Evidence$enabled  default: TRUE 
 .. return default: TRUE 
getYAML with: File$Evidence$ProteinCountThresh_num  default: 3500 
 .. return default: 3500 
getYAML with: File$Evidence$IntensityThreshLog2_num  default: 23 
 .. return default: 23 
getYAML with: File$Evidence$PeptideCountThresh_num  default: 15000 
 .. return default: 15000 
Reading file D:/R/mydirectory/PTXQC/shenhuahao-103/txt/evidence.txt ...
Requiring column(s) 'retention.length' to be of type 'numeric'!
Requiring column(s) 'retention.time.calibration' to be of type 'numeric'!
Requiring column(s) 'retention.time', 'calibrated.retention.time' to be of type 'numeric'!
Requiring column(s) 'match.time.difference' to be of type 'numeric'!
Requiring column(s) 'intensity' to be of type 'numeric'!
Requiring column(s) 'mass.error..ppm.', 'mass.error..da.', 'uncalibrated.mass.error..ppm.', 'uncalibrated.mass.error..da.' to be of type 'numeric'!
Requiring column(s) 'uncalibrated...calibrated.m.z..ppm.', 'uncalibrated...calibrated.m.z..da.' to be of type 'numeric'!
Requiring column(s) 'm.z' to be of type 'numeric'!
Requiring column(s) 'score' to be of type 'numeric'!
WARNING: Could not find column regex '^fraction$' using case-INsensitive matching.
WARNING: Could not find column regex '[RK]\.Count' using case-INsensitive matching.
Requiring column(s) 'charge' to be of type 'numeric'!
Requiring column(s) 'mass' to be of type 'numeric'!
Requiring column(s) 'ms.ms.count' to be of type 'numeric'!
Keeping 17 of 62 columns!
Read 1214661 entries from D:/R/mydirectory/PTXQC/shenhuahao-103/txt/evidence.txt.
Updating colnames
Simplifying contaminants
Simplifying reverse
Adding fc.raw.file column ... done
getYAML with: File$Evidence$SpecialContaminants  default: c("MYCOPLASMA", "1") 
 .. return default: c("MYCOPLASMA", "1") 
Starting to work on EVD:Contaminant (%s) ...
... EVD:Contaminant (%s)  done
Starting to work on EVD: Pep Intensity (">%1.1f") ...
... EVD: Pep Intensity (">%1.1f")  done
Starting to work on EVD: Prot Count (">%1.0f") ...
... EVD: Prot Count (">%1.0f")  done
Starting to work on EVD: Pep Count (">%1.0f") ...
... EVD: Pep Count (">%1.0f")  done
Starting to work on EVD: RT Peak Width ...
... EVD: RT Peak Width  done
getYAML with: File$Evidence$MQpar_MatchingTimeWindow_num  default: 1 
 .. return default: 1 
getYAML with: File$Evidence$MatchBetweenRuns_wA  default: auto 
 .. return default: auto 
Starting to work on EVD: MBR Align ...
... EVD: MBR Align  done
Starting to work on EVD: MBR ID-Transfer ...
... EVD: MBR ID-Transfer  done
Starting to work on EVD: MBR auxilliary ...
... EVD: MBR auxilliary  done
Starting to work on EVD: Charge ...
... EVD: Charge  done
Starting to work on EVD: ID rate over RT ...
... EVD: ID rate over RT  done
getYAML with: File$Evidence$MQpar_firstSearchTol_num  default: 20 
 .. return default: 20 
getYAML with: File$Evidence$firstSearch_outOfCalWarnSD_num  default: 2 
 .. return default: 2 
Starting to work on EVD: MS Cal-Pre (%1.1f) ...
... EVD: MS Cal-Pre (%1.1f)  done
getYAML with: File$Evidence$MQpar_mainSearchTol_num  default: NA 
 .. return default: NA 
Starting to work on EVD: MS Cal-Post ...
... EVD: MS Cal-Post  done
Starting to work on EVD: Contaminants ...
... EVD: Contaminants  done
Starting to work on EVD: MS^2 Oversampling ...
... EVD: MS^2 Oversampling  done
getYAML with: File$MsMs$enabled  default: TRUE 
 .. return default: TRUE 
Reading file D:/R/mydirectory/PTXQC/shenhuahao-103/txt/msms.txt ...
Requiring column(s) 'missed.cleavages' to be of type 'numeric'!
Requiring column(s) 'evidence.id' to be of type 'numeric'!
Keeping 2 of 60 columns!
Read 1257721 entries from D:/R/mydirectory/PTXQC/shenhuahao-103/txt/msms.txt.
Updating colnames
Simplifying contaminants
Simplifying reverse
Adding fc.raw.file column ... done
Starting to work on MSMS: MS^2 Cal (%s) ...
... MSMS: MS^2 Cal (%s)  done
Starting to work on MSMS: %s ...
... MSMS: %s  done
getYAML with: File$MsMsScans$enabled  default: TRUE 
 .. return default: TRUE 
Reading file D:/R/mydirectory/PTXQC/shenhuahao-103/txt/msmsScans.txt ...
Requiring column(s) 'ion.injection.time' to be of type 'numeric'!
Requiring column(s) 'retention.time' to be of type 'numeric'!
Keeping 2 of 63 columns!
Error : cannot allocate vector of size 125.0 Mb
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Error: 

Parsing the file 'D:/R/mydirectory/PTXQC/shenhuahao-103/txt/msmsScans.txt' failed. See message above why. If the file is not usable but other files are ok, disable the corresponding section in the YAML config. You might also be running a foreign locale (e.g. Chinese) - switch to an English locale and make sure that txt files are encoded in ASCII (Latin-1)!

**Comment by cbielow** [comment]
R imposes an artificial virtual memory limit on Windows (on my system that's 16GB (see ?memory.limit help in R).
It seems that your dataset is too large and R requests more memory than the limit it imposed on itself.
(in theory, one could allocate a few terrabytes on a Windows 7 Enterprise x64; which would use swapping ofc).

Possible solutions (in order of feasibility); ANY of these solutions should work:
 1) disable processing of msmsScans.txt in your YAML config, i.e. 
```
MsMsScans:
    enabled: no
```
  It's the last file to be processed, so you only miss a few metrics. You can also make two separate runs of PTXQC, each using half of the input txt files (configure the YAML accordingly). Make a copy of the report before starting the second run, otherwise the report will be replaced.

 2) increase R's memory limit (this will make processing slower, and your PC unresponsive during the PTXQC run). To do this edit your dragNdrop.bat like this:
Edit this line: https://github.com/cbielow/PTXQC/blob/master/inst/dragNdrop/QC-dragdrop/createQC_dragNdrop.bat#L140 and insert  `--max-mem-size=64G`
i.e,
```
 !Iqt!\R-3.1.0\bin\x64\rscript --max-mem-size=64G --vanilla !Iqt!\compute_QC_report.R "!txt!"
```
(there is two very similar lines like this. You can change both, just to make sure :)
I used 64GB here rather arbitrarily. This should be enough to process your data. If not, increase it.

 3) find a PC with more RAM (or upgrade RAM)

 4) make PTXQC more memory efficicient -- nothing you can do about it; I'll look into it.

**Comment by cbielow** [comment]
PTXQC v0.80.2 (released just now) has a significantly reduced memory footprint and will report some memory usage stats during computation.
This should enable processing of large txt folders on smaller machines (say 4 GB memory).

**Comment by cbielow** [comment]
closing this issue.
Feel free to keep posting if you keep encountering the issue.
