### ISSUE TITLE
drag_n_Drop: error length(unique(data$n)) == 3 is not TRUE

### ISSUE THREAD

**Issue by satzel** [cbielow/PTXQC#20]
Hi Chris,

I use the drag_n_drop batch file on a Windows machine and it used to work just fine. However, we hava one Maxquant run where we can't get a report after draging the txt folder on to the batch file.

I attach a screen shot of the log file so you can see what it happening. The weird thing about it is that other maxquant folders in the same directory run through and a report is created. And I can not see what is different about this one so that the error occurs.

Maybe you can see what's going on and have an idea how we can fix this. 

Thanks
saskia

![error_ptxqc](https://cloud.githubusercontent.com/assets/10625724/14371382/752a9f84-fd7a-11e5-8a16-b2267504fbdd.JPG)

**Comment by cbielow** [comment]
The error you see was fixed (I would need to look up when exactly).

Solution: please update to the latest version of PTXQC (see https://github.com/cbielow/PTXQC/tree/master/inst/dragNdrop --> Update).

If you want to keep working with the version that you have, you must disable evidence.txt, i.e. you will loose most of the interesting metrics (not recommended).
