### ISSUE TITLE
Error : length(unique(data$n)) == 3 is not TRUE - STILL after update

### ISSUE THREAD

**Issue by satzel** [cbielow/PTXQC#23]
Hi Chris,

sorry to be a pain but I updated to the newest version and tried the same folder that was acting up before but I get the same error. I tried the dragndrop and the R script.
Here I attach the error from the R script with all packages I loaded.
Maybe I screwed something else up, or is it the data itself?

Thanks again
Saskia
![error_ptxqc_again](https://cloud.githubusercontent.com/assets/10625724/14552584/31ca8fe8-0323-11e6-89e0-ccb5e7d48324.JPG)

**Comment by cbielow** [comment]
ouch.
Can you send me the data?! Evidence.txt should suffice.
I'll look into it ASAP.


Am 4/15/2016 um 8:00 AM schrieb Saskia:

**Comment by satzel** [comment]
sure, how/where do you want me to send it? So I send you the whole txt folder?

thanks for your help

**Comment by cbielow** [comment]
evidence.txt would do it, but sending the whole thing does not hurt either.
Can you upload it somewhere and send me the link (my email is in the 
PTXQC/DESCRIPTION file).
If its only evidence.txt, a zipped email attachment will also be fine.
as long as its <10MB.


Am 4/15/2016 um 8:08 AM schrieb Saskia:

**Comment by cbielow** [comment]
the bug is fixed in https://github.com/cbielow/PTXQC/commit/574fcc4d2ec00cd21eb389b3f481bb2f7a429e7d
(PTXQC v0.80.5)

Please let me know if this fixes your problem.
