### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by sjefboeren** [cbielow/PTXQC#24]
[Installation PTXQC console second attempt.pdf](https://github.com/cbielow/PTXQC/files/317966/Installation.PTXQC.console.second.attempt.pdf)
[Installation PTXQC console.pdf](https://github.com/cbielow/PTXQC/files/317965/Installation.PTXQC.console.pdf)

I tried installation from 2 different cran mirror sites. Seems like PTXQC was not installed. Please help finishing the installation.

Thank you,

Sjef

PS  Also the help server gives an error:
![error ptxqc help website no package named ptxqc could be found](https://cloud.githubusercontent.com/assets/19970742/16110503/58d2dad0-33ae-11e6-95c2-d83cb949c83d.jpg)

**Comment by cbielow** [comment]
Hi Sjef,

the first time, Vignette creation failed -- my guess would be because 
Pandoc was not in the PATH (i.e. R would need a restart after you 
installed Pandoc as detailed in the installation manual).

The second time, vignettes were build -- good so far.
But then the documentation was not found.
Not sure why this happens; could be a bug in Devtools, or in R itself, 
OR: because your user folders are pointing to a network drive ( 
'\\SCOMP0850/boere001$/My Documents/R....'). This is somewhat unusual, 
and might be the reason, but its impossible to debug from here.

A possible solution: using the R console try to build the package 
without vignettes, i.e.

library("devtools")
install_github("cbielow/PTXQC", build_vignettes = FALSE)

If that does not work, we can think about something else.


Am 6/16/2016 um 10:38 AM schrieb sjefboeren:

**Comment by sjefboeren** [comment]
Hi Chris,

Thank you for the fast reply.
I am working on a university computer that stores settings on a network drive. I do run R from my computer though. I did change the working directory but that does not seem to change anything.
Looks like i get a few steps further following your suggestions but still the package PTXQC cannot be found. Anything else i can try?

Thank you,
Sjef

[cid:image002.png@01D1C7C0.81AE0A10]

**Comment by cbielow** [comment]
Can you post the output when building without vignettes?

Am 6/16/2016 um 11:16 AM schrieb sjefboeren:

**Comment by sjefboeren** [comment]
To get an output i need to start PTXQC i suppose. But it has not been installed? Or do you mean a R console dump like before? That’s attached.
Thanks,
Sjef

**Comment by cbielow** [comment]
> To get an output i need to start PTXQC i suppose. But it has not been
> installed? Or do you mean a R console dump like before?

Yes.

> That’s attached.

I dont see it...

**Comment by sjefboeren** [comment]
Sorry, here it is

**Comment by cbielow** [comment]
?

maybe the attachment is too large?

**Comment by cbielow** [comment]
mhh.. I'm still wondering if its your network-home that is causing the trouble...
So lets try to fix this first:

In an R console do:

> library("devtools")
 ## this should give you a list of your usual R library directories
> .libPaths()  
 ## we use a new library (in particular not a network drive) -- please create this folder beforehand
>.libPaths("c:\\tempLib") 
## lets try to install PTXQC
> install_github("cbielow/PTXQC", build_vignettes = FALSE)

If that worked, PTXQC is now in 'c:\tempLib'. Go there with your file explorer and copy the PTXQC directory into '\\SCOMP0850/boere001$/My Documents/R/win-library/3.1' (which should be your regular R library).
Then restart R and do
> library(PTXQC)

If that works, you're golden :)

**Comment by sjefboeren** [comment]
Hi Chris,

Your last suggestion still did not completely install PTXQC as you can see below. But indeed it probably has to do with the R configuration. I simply tried to install PTXQC on another (non-university) computer and it worked immediately. Thank you for your fast help with the installation.

The desktop shortcut is great. Take a txt directory and drop it on there. That’s how we (non-programmers) like it.
I ran PTXQC a few times on a some 1h injections and In the Command prompt window I always see:

[cid:image004.jpg@01D1C88C.0AEE2190]

Should I be alarmed to have so many warnings?

I will now test some different settings more suitable for our instrument (LTQ-Orbitrap XL) and standard (1h) gradient.

Thank you,

Sjef



[cid:image001.png@01D1C87D.C211F900]

**Comment by cbielow** [comment]
good to hear it worked out.

The images did not make it to GitHub -- maybe just use the Github page directly (your can just drag'n'drop images into the textbox) instead of email.
In general, a few warnings are normal ...

**Comment by cbielow** [comment]
will close the ticket; the issue is with the `devtools` package.
