### ISSUE TITLE
missing MBR plots

### ISSUE THREAD

**Issue by sjefboeren** [cbielow/PTXQC#25]
Thank you for this wonderful QC software. I do see a few possibilities for improvement though.
I like the Match Between runs plots very much. But, sometimes there are no graph’s in the “EVD: alignment” check page. A remark appears: Could not find a unique reference Raw file even though the data in the Evidence table seem okay. Changing “MatchBetweenRuns_wA” from auto to yes did not help. Can the software be changed to just show the data in the Evidence table?
Another issue that needs changes has to do with the injection naming. Short names nor best effort names are taken over in the PCA plots, PG: (LFQ) intensity distribution plots and PG: Contaminant per condition plot. Can it be changed to show the short name?

Thank you very much,

Sjef Boeren

[report_v0.80.7_combined.pdf](https://github.com/cbielow/PTXQC/files/393367/report_v0.80.7_combined.pdf)
[evidence.txt](https://github.com/cbielow/PTXQC/files/393368/evidence.txt)

**Comment by cbielow** [comment]
concerning 

issue 1: Your data is just too good :-) I made the check less stringent and it should produce a plot now 
![image](https://cloud.githubusercontent.com/assets/6008722/17300671/aa5e486a-5813-11e6-9289-df147b47bcce.png)

issue 2: the PCA plot works on data from proteinGroups.txt, where the groups do not neccesarily correspond 1:1 to Raw files (for which the user can set names manually in `report_vXYZ_filename_sort.txt`). So until I find time to also allow users to manually influence that mapping, the only other way is to use shorter names when assigning groups during MaxQuant configuration OR (for the tech savvy) shorten the names in proteinGroups.txt before running PTXQC.
I added a small note to the help section of the Html report.

The fixes will be available tomorrow on Github after a suite of tests runs through.

Thanks for reporting!

**Comment by sjefboeren** [comment]
Thanks Chris. How about adding an extra column "group name" to ...filename_sort.txt table? By the way, what is the 'best effort' column used for?
Best regards,
Sjef

**Comment by cbielow** [comment]
'best effort' is not used by PTXQC but is rather for informative purposes, so the user can see where/why the shortening does not work. Also, its a good basis to manually edit the names if user wants to replace the 2nd column with 'file x'...

**Comment by cbielow** [comment]
The extra-column for experimental groups is probably the way to go. The easiest way to do this is probably via 'raw file' and 'experiment' column in evidence.txt. Will open a separate ticket and close this one.
