### ISSUE TITLE
Installing Fixed version

### ISSUE THREAD

**Issue by sjefboeren** [cbielow/PTXQC#27]
Hi Chris,
I have PTXQC installed in C:\PTXQC. I tried to install the latest fix by running the R-scripts:

if (!require(devtools, quietly = TRUE)) install.packages("devtools")
library("devtools")
install_github("cbielow/PTXQC", build_vignettes = TRUE)

This gave the following messages:

Installing PTXQC
Installing 1 package: digest
Installing package into ‘C:/Users/LCMS/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.3/digest_0.6.10.zip'
Content type 'application/zip' length 169641 bytes (165 KB)
downloaded 165 KB

package ‘digest’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘digest’

The downloaded binary packages are in
        C:\Users\LCMS\AppData\Local\Temp\Rtmpk3Ie2C\downloaded_packages
"C:/PROGRA~1/R/R-33~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD build  \
  "C:\Users\LCMS\AppData\Local\Temp\Rtmpk3Ie2C\devtools1a243e78436c\cbielow-PTXQC-e37facc" --no-resave-data --no-manual 

* checking for file 'C:\Users\LCMS\AppData\Local\Temp\Rtmpk3Ie2C\devtools1a243e78436c\cbielow-PTXQC-e37facc/DESCRIPTION' ... OK
* preparing 'PTXQC':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
Warning: running command '"C:/PROGRA~1/R/R-33~1.0/bin/x64/Rcmd.exe" INSTALL -l "C:\Users\LCMS\AppData\Local\Temp\Rtmp0e3KiO\Rinst322851fc84a" --no-multiarch "C:/Users/LCMS/AppData/Local/Temp/Rtmp0e3KiO/Rbuild3228b67691b/PTXQC"' had status 1
      -----------------------------------
* installing *source* package 'PTXQC' ...
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'digest'
ERROR: lazy loading failed for package 'PTXQC'
* removing 'C:/Users/LCMS/AppData/Local/Temp/Rtmp0e3KiO/Rinst322851fc84a/PTXQC'
      -----------------------------------
ERROR: package installation failed
Error: Command failed (1)

Now trying to run PTXQC on a MaxQuant result it used to work on before gives the following messages in a Windows command screen:

This batch file allows invoking 'createQC_dragNdrop.bat'
with a YAML config file which resides in this directory.

Using 'C:\PTXQC\dragNdrop\QC-dragdrop\\config.yaml' as YAML config

This batch file is used to invoke the QC script by drag'n'dropping of
a MaxQuant txt folder (or any file within) onto this .bat file.
Within the same txt folder, a QC report in Html/PDF format will be created.

First time installation of this script [for admins only]:
The script expects a certain structure to be present.
This .bat file expects a subfolder named '_internal'
which holds:
     'R-3.3.0'             Holds a complete R installation
                           (including all packages required to run the
                            PTXQC package)
     'compute_QC_report.R' The R script that is invoked by this .bat

Found QC directory at 'C:\PTXQC\dragNdrop\QC-dragdrop\\_internal'

-- 'F:\2016\16_07_25_Moheb_Jos_Francesca\Francesca\combined\txt' is a directory
Txt folder is at 'F:\2016\16_07_25_Moheb_Jos_Francesca\Francesca\combined\txt'

Yaml file is: C:\PTXQC\dragNdrop\QC-dragdrop\config.yaml

Using YAML configuration file "C:\PTXQC\dragNdrop\QC-dragdrop\config.yaml"

Found R at '"C:\PTXQC\dragNdrop\QC-dragdrop\\_internal"\R-3.3.0\bin\x64\rscript.exe'.

Using YAML "C:\PTXQC\dragNdrop\QC-dragdrop\config.yaml" file and calling R now ...

Calling '"C:\PTXQC\dragNdrop\QC-dragdrop\\_internal"\R-3.3.0\bin\x64\rscript.exe --vanilla "C:\PTXQC\dragNdrop\QC-dragdrop\\_internal"\compute_QC_report.R F:\2016\16_07_25_Moheb_Jos_Francesca\Francesca\combined\txt "C:\PTXQC\dragNdrop\QC-dragdrop\config.yaml"'
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
  there is no package called 'digest'
Error: package or namespace load failed for 'PTXQC'
Execution halted
Failed folder F:\2016\16_07_25_Moheb_Jos_Francesca\Francesca\combined\txt. Does it exist and is writeable!?
Access is denied.

The error should be indicated above.
Common errors are (yours might be different)
  - your R installation runs out of memory; especially if its 32bit
  - the file 'C:\PTXQC\dragNdrop\QC-dragdrop\\_internal\compute_QC_report.R' is missing

If the error persists, follow the
instructions on https://github.com/cbielow/PTXQC
in the section 'Bug reporting'.

Leave this window open until the bug report is submitted

You can copy the text from this window by
  1) right-clicking here
  2) choose 'Select all'
  3) press the 'Enter' key
  4) paste it somewhere (issue ticket, email)
This ensures that all text is available to debug the problem.
Thanks!
Press any key to continue . . .

Please tell me how to get PTXQC working again with the fix.
Thank you,
Sjef Boeren

**Comment by cbielow** [comment]
Hi,

it seems that package installation fails.
The noteworthy line here is:

 > Warning: cannot remove prior installation of package ‘digest’

So your digest package is probably broken now and hence PTXQC will not run.

Reasons why it broke can be manifold, but it seems that its usually due 
to multiple R-sessions (which lock the package files and prevent them 
from being updated), see

http://stackoverflow.com/questions/26570912/error-in-installation-a-r-package

Try to close all R-sessions, start a fresh R session and install again. 
That should hopefully fix it.

cheers
Chris




Am 8/3/2016 um 12:41 PM schrieb sjefboeren:

**Comment by sjefboeren** [comment]
Hi Chris, I tried several times (5*) even after a complete system restart. I reproducibly get:

> if (!require(devtools, quietly = TRUE)) install.packages("devtools")
Warning message:
package ‘devtools’ was built under R version 3.3.1 
> library("devtools")
> install_github("cbielow/PTXQC", build_vignettes = TRUE)
Downloading GitHub repo cbielow/PTXQC@master
from URL https://api.github.com/repos/cbielow/PTXQC/zipball/master
Installing PTXQC
"C:/PTXQC/dragNdrop/QC-dragdrop/_internal/R-3.3.0/bin/x64/R" --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD build  \
  "C:\Users\LCMS\AppData\Local\Temp\RtmpuG7Emp\devtools470428f65d4\cbielow-PTXQC-e37facc"  \
  --no-resave-data --no-manual 

* checking for file 'C:\Users\LCMS\AppData\Local\Temp\RtmpuG7Emp\devtools470428f65d4\cbielow-PTXQC-e37facc/DESCRIPTION' ... OK
* preparing 'PTXQC':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ...Warning: running command '"C:/PTXQC/DRAGND~1/QC-DRA~1/_INTER~1/R-33~1.0/bin/x64/Rscript" --vanilla --default-packages= -e "tools::buildVignettes(dir = '.', tangle = TRUE)"' had status 1
 ERROR
trying URL 'ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2015/11/PXD003133/txt_20min.zip'
Quitting from lines 33-57 (PTXQC-Basic_Guide_for_R_users.Rmd) 
Error: processing vignette 'PTXQC-Basic_Guide_for_R_users.Rmd' failed with diagnostics:
cannot open URL 'ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2015/11/PXD003133/txt_20min.zip'
Execution halted
Error: Command failed (1)

Is there another way to install the fix only?
Thanks,
Sjef

**Comment by cbielow** [comment]
It seems that the vignettes could not be build because PRIDE was 
temporarily offline. The link in the error message is working again 
(from here at least), but if that error keeps occurring you can install 
the package simply without vignettes, i.e.

install_github("cbielow/PTXQC", build_vignettes = FALSE)

this omits the part where the error occurs. Downside: no offline 
vignettes for PTXQC -- but you can always look them up on GitHub.



Am 8/4/2016 um 9:50 AM schrieb sjefboeren:

**Comment by sjefboeren** [comment]
Great Chris. That worked immediately. 
Thanks, 
Sjef
