### ISSUE TITLE
Modifications

### ISSUE THREAD

**Issue by sjefboeren** [cbielow/PTXQC#28]
Hi Chris,
It could be useful to add the top 5 modifications (similar to the top 5 contaminants) for those who use the 'dependent peptides' option. Is that possible?
Kind regards,
Sjef

**Comment by cbielow** [comment]
You mean to assess if including another var.mod in the default search could potentially benefit?!
Certainly possible.
The disadvantage here is that we'd need to parse yet another file (allPeptides.txt) -- its not huge, so should be doable.

**Comment by sjefboeren** [comment]
Also yes. But most of all to be able to compare the amount of modifications to other datasets. I think it makes sense to express the top 5 modifications relatively to the total amount of identifications as a %.

You can use allPeptides.txt but also the smaller file msmsScans.txt has the same info needed in columns DP cluster size, DPCluster Mass, DP Modification and DP Probabilities.

**Comment by cbielow** [comment]
prototype using just the dp.modification column. x-axis is relative to total number of non-DP (regular) identified peptides.

![image](https://cloud.githubusercontent.com/assets/6008722/19799691/3d367a9e-9cf8-11e6-9b76-ac2dbdfa7ef5.png)

**Comment by sjefboeren** [comment]
Yes, Chris. It has the info needed and your example looks good. I think it will work even for large amounts of (related) samples.

**Comment by cbielow** [comment]
the feature is implemented now (v0.82.0) -- please try on your data and let know what you think.

**Comment by sjefboeren** [comment]
Very nice Chris. Possible improvements:

-      Remove the “unmodified” peptides from the plots. This info cannot be used anyway.

-      Place more runs in one graph. More like you did for the intensity distributions. This improves the overview.

-      It would also be helpful to use the same colour for the same modification. Most common modifications are:
Oxidation
De-amidation
Carbamidomethyl
Carbamyl
Methylation
Di-methylation
Ethylation
Formylation
Hydroxylation
Di-hydroxylation
Loss of ammonia
Loss of water
And of course the rest group “Other”.
When someone wants to use the info to adjust the modifications set in MaxQuant, it would also be nice to know whether a certain site/amino acid prevalently becomes modified (from DP AA). Is it possible to add this?

BTW The yellow colour used sometimes is very difficult to see. Use a thicker line like you did for the peak widths.

Thanks.
Sjef

**Comment by cbielow** [comment]
> Very nice Chris. Possible improvements:
>
> - Remove the “unmodified” peptides from the plots. This info cannot be
> used anyway.

They might help, maybe to optimize collision energies etc...but its far 
fetched, so I switched them off.

>
> - Place more runs in one graph. More like you did for the intensity
> distributions. This improves the overview.

ok.

>
> - It would also be helpful to use the same colour for the same
> modification. Most common modifications are:
> Oxidation
> De-amidation
> Carbamidomethyl
> Carbamyl
> Methylation
> Di-methylation
> Ethylation
> Formylation
> Hydroxylation
> Di-hydroxylation
> Loss of ammonia
> Loss of water
> And of course the rest group “Other”.

Hard to do, since its hard to come up with ~12 distinct colors. I'll 
leave the color assignment as is (most frequent mod gets  blue, etc..)

> When someone wants to use the info to adjust the modifications set in
> MaxQuant, it would also be nice to know whether a certain site/amino
> acid prevalently becomes modified (from DP AA). Is it possible to add this?

Its a bit more parsing (since each DP has potentially more than 1 site). 
this also skews the stats a bit (i.e. which one is correct?)

>
> BTW The yellow colour used sometimes is very difficult to see. Use a
> thicker line like you did for the peak widths.

agreed.

**Comment by cbielow** [comment]
![image](https://cloud.githubusercontent.com/assets/6008722/19937979/849b395e-a123-11e6-9599-c65ca4e2cd69.png)

most frequent sites are given in the legend now.

**Comment by sjefboeren** [comment]
Excellent Chris. Thank you very much.
Sjef
