### ISSUE TITLE
pandoc / html issue

### ISSUE THREAD

**Issue by Deanho** [cbielow/PTXQC#29]
Hi. Firstly, PTXQC is a very nice and useful tool. Thanks. When I installed and ran PTXQC and Pandoc the first time, everything went perfectly, and all the required reports were generated. However, since then, every time I try to run it, everything works EXCEPT the writing of the html report. Any ideas what is happening? I run it from R (simply using createReport(txt_folder)). Does Pandoc have to be in the windows PATH? Do I have to tell PTXQC where to look for Pandoc? When I installed Pandoc initially, it was installed in my /User/AppData folder (rather than Program Files). At present it is in my RStudio/bin directory. Could this be causing problems? Where should Pandoc be in my path? Thanks. Dean

**Comment by cbielow** [comment]
my guess is that moving Pandoc caused the trouble.
On my system Pandoc resides in "C:/Program Files/RStudio/bin/pandoc" by default and the rmarkdown package seems to find it without trouble.
It does so (warning speculation), by looking at the environment variable [1]

> Sys.getenv("RSTUDIO_PANDOC")
[1] "C:/Program Files/RStudio/bin/pandoc"

Weirdly, 'RSTUDIO_PANDOC' is only defined within RStudio, not in my global Windows environment.
Also a "where pandoc" in cmd.exe yields nothing, i.e. pandoc is not found via PATH. I guess "RSTUDIO_PANDOC" is a good place to start investigating.


[1] [http://stackoverflow.com/questions/28432607/pandoc-version-1-12-3-or-higher-is-required-and-was-not-found-r-shiny]

**Comment by cbielow** [comment]
did this fix your issue?
I will close this ticket for now. Please feel free to re-open.

**Comment by Deanho** [comment]
Hi Chris,

I didn’t actually, but got side-tracked….
I may be in touch in the future again.
Regards,

Dean
