### ISSUE TITLE
can not installation

### ISSUE THREAD

**Issue by pariswu1988** [cbielow/PTXQC#35]
Hi, Thanks for so great package for us
we have used PTXQC for long time, and it helps us a lot.
But recently, it does not work.
detail is that:
when go to the command:
 r = createReport(txt_folder)
it reports a error:
Error in createReport(txt_folder) : 
  Argument txt_folder with value 'E:ping/shenghuahao/zhangchao/combined/txt' is not a valid directory

Maybe it because of upgrade of package,
So I re-install the package, but there comes another error:

"package ‘yaml’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘yaml’
"E:/software/R-3.2.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD build  \
  "C:\Users\waters\AppData\Local\Temp\Rtmpcb0kmH\devtools77201644292\cbielow-PTXQC-4e736c6" --no-resave-data --no-manual 

* checking for file 'C:\Users\waters\AppData\Local\Temp\Rtmpcb0kmH\devtools77201644292\cbielow-PTXQC-4e736c6/DESCRIPTION' ... OK
* preparing 'PTXQC':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
Warning: running command '"E:/software/R-32~1.3/bin/x64/Rcmd.exe" INSTALL -l "C:\Users\waters\AppData\Local\Temp\Rtmp40dupV\Rinst998c4cce6cf2" --no-multiarch "C:/Users/waters/AppData/Local/Temp/Rtmp40dupV/Rbuild998c47314e53/PTXQC"' had status 1
      -----------------------------------
ERROR: dependencies 'plyr', 'reshape2', 'seqinr', 'yaml' are not available for package 'PTXQC'
* removing 'C:/Users/waters/AppData/Local/Temp/Rtmp40dupV/Rinst998c4cce6cf2/PTXQC'
      -----------------------------------
ERROR: package installation failed
Error: Command failed (1)"

Thanks!

**Comment by cbielow** [comment]
Hey,

thanks for the feedback!

This sounds like R cannot uninstall YAML, since its being used
Have you tried to update the package using a fresh/clean R console (i.e. no pre-loaded packages etc).

If that does not help, maybe manuallz deleting the package directories in the UserLibrary while R is not running will do the trick.

Let me know if that helps :)

cheers
Chris
