### ISSUE TITLE
No report build

### ISSUE THREAD

**Issue by fcsigloch** [cbielow/PTXQC#48]
Hi Chris,

I freshly installed PTQXC v 0.92.3 from Github, following your instructions. Everything went fine during installation, using R-3.4.3 and Windows 10.

When I tried to produce a report by drag-and-drop, I ran into an error. Checking the log file, I saw that PTQXC expected an `mqpar.xml` in the `txt` folder, so I copied the file to that location. However, the error persists. 

There seem to be two problems:
1) Many columns in the `.txt`-files are not recognized as `numeric`.
2) The command line ended in (I manually added this to the log file for convience):
```
Quitting from lines 75-111 (PTXQC_report_template.Rmd)

Error in FUN(X[[i]], ...) : Objekt 'PC2' nicht gefunden
Zusätzlich: Warnmeldungen:
1: Using alpha for a disecrete variable is not advised.
2: Using alpha for a disecrete variable is not advised.
```
No PDF or HTML file was created. Only one PNG file was created in the folder `figure-html`. I attached all files created by PTXQC [here](https://github.com/cbielow/PTXQC/files/2376101/ptxqc_error.zip).

Greetings,
Florian

**Comment by cbielow** [comment]
ok, thanks for the bug report.
But without the .txt files, its gonna be hard to fix. Can you upload and send a link via email?

(passing comment: mqpar.xml is not required, but allows to have better parameter estimates for scoring)

**Comment by cbielow** [comment]
maybe its enough to send one txt file (evidence.txt, maybe proteinGroups.txt). Just try locally to find a minimal set to reproduce the error.

**Comment by fcsigloch** [comment]
The error seems to be dependent on the MQ analysis. It worked for others that I ran recently. If I can find the difference, I will post it.
