### ISSUE TITLE
Shortened raw file names are not unique. Error during report generating - v0.92.4

### ISSUE THREAD

**Issue by mikulasekkamil** [cbielow/PTXQC#49]
Hi PTXQC team,

during the report generating the following error message appeared: 

While loading MQ data: shortened raw filenames are not unique! This should not happen. Please contact the developers and provide the above names!

Adding fc.raw.file column ...Original names:
3265_Lumik3_Shakya_150IS_HCD_11A_1 3265_Lumik3_Shakya_150IS_HCD_11B_1 3265_Lumik3_Shakya_150IS_HCD_11C_1 3265_Lumik3_Shakya_150IS_HCD_11D_1 3265_Lumik3_Shakya_150IS_HCD_12A_1 3265_Lumik3_Shakya_150IS_HCD_12B_1 3265_Lumik3_Shakya_150IS_HCD_12C_1 3265_Lumik3_Shakya_150IS_HCD_12D_1 3265_Lumik3_Shakya_150IS_HCD_13A_1 3265_Lumik3_Shakya_150IS_HCD_13B_1 3265_Lumik3_Shakya_150IS_HCD_13C_1 3265_Lumik3_Shakya_150IS_HCD_13D_1 3265_Lumik3_Shakya_150IS_HCD_14A_1 3265_Lumik3_Shakya_150IS_HCD_14B_1 3265_Lumik3_Shakya_150IS_HCD_14C_1 3265_Lumik3_Shakya_150IS_HCD_14D_1Short names:
........_1 ........_1 ........_1 ........_1 ........_1 ........_1 ........_1 ........_1 ........_1 ........_1 ........_1 ........_1 ........_1 ........_1 ........_1 ........_1Error in res(x, ...) :

version 0.92.4 **not working**
version 0.90.0 **working**
MQ version 1.6.2.10

Thanks for support
Kind regards
Kamil Mikulasek

Proteomics Core Facility and Zbynek Zdrahal Research Group
CEITEC-MU
Masaryk University

**Comment by cbielow** [comment]
thanks for reporting this.
This is fixed in v0.92.05 (available on CRAN in the next hours) -- commit https://github.com/cbielow/PTXQC/commit/01aa0296bcaf58678ae0051b3c6fd3d933b65d94

Will close. Feel free to re-open if error persists.
