### ISSUE TITLE
How to use it??

### ISSUE THREAD

**Issue by soerendip** [cbielow/PTXQC#53]
Is there an example how to use the app?
When I do 

`browseVignettes(package = 'PTXQC')`
I get 

> Error in unlist(str_split(x, "\n"), recursive = FALSE, use.names = FALSE): lazy-load database '/home/.../miniconda3/envs/py3/lib/R/library/stringr/R/stringr.rdb' is corrupt
> Traceback:

**Comment by cbielow** [comment]
This seems like a general R issue. Usually restarting the rsession solves it for me, but Google probably knows more.
In terms of vignette, you can see the them here on Github as well. Just browse the folders.

**Comment by soerendip** [comment]
It would be nice to have a working example somewhere given a txt folder is already present.

**Comment by cbielow** [comment]
As I said, have a look at the vignettes.
For example, https://github.com/cbielow/PTXQC/blob/master/vignettes/PTXQC-Basic_Guide_for_R_users.Rmd
It boils down to
```
library(PTXQC)
r = createReport("c:/my/txt/folder/")
```

**Comment by soerendip** [comment]
Thanks that would be helpful to have on the front page.
