### ISSUE TITLE
PTXQC for Bruker's TimsTOF data

### ISSUE THREAD

**Issue by fazeliniah** [cbielow/PTXQC#54]
Hi PTXQC team,
I tried to test PTXQC for the MaxQuant output of Bruker's TimsTOF raw data. Unfortunately it failed to generate any result. I have attached the log file for your review. 
I have a feeling this may not be an easy fix. I am wondering if you have any plans to expand your valuable PTXQC for the TimsTOF data that is gaining popularity. 
Thanks
Hossein
 
[report_v0.92.3.log](https://github.com/cbielow/PTXQC/files/3080628/report_v0.92.3.log)

**Comment by cbielow** [comment]
the log does not contain the error message unfortunately.
Can you upload the txt-folder somewhere and send the link (either here or via email to chris.bielow@bsc.fu-berlin.de if the data is sensitive)

**Comment by cbielow** [comment]
Thanks for sending the data.
Issue is fixed in v0.92.6, available on GitHub and CRAN (hopefully in a few hours).

Thanks for reporting the issue; please re-open the ticket if problem persists.
