### ISSUE TITLE
Error in !df_msms$contaminant

### ISSUE THREAD

**Issue by marioernestovaldes** [cbielow/PTXQC#55]
Hello! I am trying to run an analysis with PTXQC. The thing is when I try to analyze the entire 'txt' folder this error comes up:

... MSMS: MS^2 Cal (%s)  done
Starting to work on MSMS: %s ...
Error in !df_msms$contaminant : invalid argument
Also: Warning message:
Using alpha for a discrete variable is not advised

could you please help me?

see attached the msms files I am currently using...

thanks in advance!

Mario
[msms_files.zip](https://github.com/cbielow/PTXQC/files/3087115/msms_files.zip)

**Comment by cbielow** [comment]
[report_v0.92.6_msms_files.pdf](https://github.com/cbielow/PTXQC/files/3088816/report_v0.92.6_msms_files.pdf)

(Github only supports uploading PDFs out of the box -- no Html report -- sorry)
