### ISSUE TITLE
Error in data.table(df_reps)

### ISSUE THREAD

**Issue by marioernestovaldes** [cbielow/PTXQC#56]
Hello there! Thanks for your quick replay in https://github.com/cbielow/PTXQC/issues/55... 

Now, I having a problem with the analysis of the information from 'evidence' file. In fact, the information of this file is missing when I ran the analysis over the entire 'txt' folder. see attached the 'evidence' file I am using and the report from PTXQC... see below the error... 

Starting to work on EVD: Reporter intensity ...
Error in data.table(df_reps) :
  "data.table" fucntion not found

let me know if you need other info...

thanks in advance... your help is really appreciated...

Mario

[report_v0.92.6.log](https://github.com/cbielow/PTXQC/files/3091056/report_v0.92.6.log)
[evidence.txt](https://github.com/cbielow/PTXQC/files/3091057/evidence.txt)

**Comment by cbielow** [comment]
I cannot reproduce the issue.
How did you invoke PTXQC? It looks like the package dependencies (data.table package in this case) are not loaded.
What happens when you run `library(data.table)`?

**Comment by marioernestovaldes** [comment]
This is the command I am using

.\createQC_dragNdrop.bat D:\Programs\QCdir\QC-dragdrop\txt_folder\

txt_flder only contains evidence file

when I ran library(data.table) in R, this is what comes up:

data.table 1.12.2 using 3 threads (see ?getDTthreads).  Latest news:
r-datatable.com

please, let me know if you need other info

thanks

**Comment by cbielow** [comment]
mhh.. this is a hard one...
When opening R, did you use the R version which is installed in `_internal\R...` or your default R installation? (the latter might have packages installed which the Drag'n'Drop version does not have access to). Actually the dragndrop.bat goes to great length to ensure that these two installations are not coupled (by setting $R_LIBS environment for example).
So debugging this is also a bit tricky, since each R installation might behave differently.
I still suspect that data.table is not properly installed in the dragndrop R installation.... but its hard to tell.

Can you try to execute
```
library(PTXQC)
createReport("D:\\Programs\\QCdir\\QC-dragdrop\\txt_folder")
```

in your R installation and see what happens?
If it runs successfully, then repeat the copy/installation process for `./_internal/...`. Hopefully that fixes the other R installation which is invoked by the bat file.

**Comment by marioernestovaldes** [comment]
I tried to run your command in both installations and this is the output:

> library(PTXQC)
Loading package PTXQC (version 0.92.6)
> createReport("D:\\Programs\\QCdir\\QC-dragdrop\\txt_folder", list())
YAML: PTXQC$ReportFilename$extended def: TRUE
YAML: PTXQC$UseLocalMQPar def: TRUE
YAML: File$Parameters$enabled def: TRUE
YAML: PTXQC$NameLengthMax_num def: 10
YAML: File$Summary$enabled def: TRUE
YAML: File$Summary$IDRate$Thresh_bad_num def: 20
YAML: File$Summary$IDRate$Thresh_great_num def: 35
YAML: File$ProteinGroups$enabled def: TRUE
YAML: File$ProteinGroups$RatioPlot$LabelIncThresh_num def: 4
YAML: File$ProteinGroups$IntensityThreshLog2_num def: 25
YAML: File$Evidence$enabled def: TRUE
YAML: File$Evidence$ProteinCountThresh_num def: 3500
YAML: File$Evidence$IntensityThreshLog2_num def: 23
YAML: File$Evidence$PeptideCountThresh_num def: 15000
YAML: File$Evidence$SpecialContaminants def: c(name = "MYCOPLASMA", threshold = "1")
YAML: File$Evidence$MQpar_MatchingTimeWindow_num def: 1
Warning in getMQPARValue(txt_files$mqpar, "matchingTimeWindow") :
  The file 'D:\Programs\QCdir\QC-dragdrop\txt_folder/mqpar.xml' was not found. MaxQuant parameters could not be extracted. Will fall back to default value, which however is only an approximation. Please either: a) copy the mqpar.xml which was used for this MQ analysis into your TXT folder or, b) make sure that you configure all YAML parameters whose name starts with 'MQpar_' correctly.
YAML: File$Evidence$MatchBetweenRuns_wA def: auto
YAML: File$Evidence$MQpar_firstSearchTol_num def: 20
Warning in getMQPARValue(txt_files$mqpar, "firstSearchTol") :
  The file 'D:\Programs\QCdir\QC-dragdrop\txt_folder/mqpar.xml' was not found. MaxQuant parameters could not be extracted. Will fall back to default value, which however is only an approximation. Please either: a) copy the mqpar.xml which was used for this MQ analysis into your TXT folder or, b) make sure that you configure all YAML parameters whose name starts with 'MQpar_' correctly.
YAML: File$Evidence$firstSearch_outOfCalWarnSD_num def: 2
YAML: File$Evidence$MQpar_mainSearchTol_num def: NA
Warning in getMQPARValue(txt_files$mqpar, "mainSearchTol") :
  The file 'D:\Programs\QCdir\QC-dragdrop\txt_folder/mqpar.xml' was not found. MaxQuant parameters could not be extracted. Will fall back to default value, which however is only an approximation. Please either: a) copy the mqpar.xml which was used for this MQ analysis into your TXT folder or, b) make sure that you configure all YAML parameters whose name starts with 'MQpar_' correctly.
Warning in createReport("D:\\Programs\\QCdir\\QC-dragdrop\\txt_folder",  :
  PTXQC: Cannot draw borders for calibrated mass error, since neither 'File$Evidence$MQpar_mainSearchTol_num' is set nor a mqpar.xml file is present!
YAML: File$MsMs$enabled def: TRUE
YAML: File$MsMsScans$enabled def: TRUE
YAML: File$MsMsScans$IonInjectionThresh_num def: 10
YAML: PTXQC$OutputFormats def: html,plainPDF
YAML: PTXQC$PlainPDF$AddPageNumbers def: on
YAML: order$qcMetric_PAR def: 1
YAML: order$qcMetric_PG_PCA def: 3
YAML: order$qcMetric_EVD_Top5Cont def: 10
YAML: order$qcMetric_PG_Ratio def: 19
YAML: order$qcMetric_EVD_UserContaminant def: 20
YAML: order$qcMetric_EVD_PeptideInt def: 30
YAML: order$qcMetric_EVD_ReporterInt def: 31
YAML: order$qcMetric_PG_RawInt def: 32
YAML: order$qcMetric_PG_LFQInt def: 33
YAML: order$qcMetric_PG_ReporterInt def: 34
YAML: order$qcMetric_MSMS_MissedCleavages def: 40
YAML: order$qcMetric_EVD_Charge def: 100
YAML: order$qcMetric_PG_Cont def: 110
YAML: order$qcMetric_MSMSScans_TopNoverRT def: 120
YAML: order$qcMetric_EVD_IDoverRT def: 150
YAML: order$qcMetric_EVD_RTPeakWidth def: 170
YAML: order$qcMetric_EVD_MBRAlign def: 210
YAML: order$qcMetric_EVD_MBRIdTransfer def: 220
YAML: order$qcMetric_EVD_MBRaux def: 221
YAML: order$qcMetric_MSMSScans_IonInjTime def: 240
YAML: order$qcMetric_MSMSScans_MSMSIntensity def: 245
YAML: order$qcMetric_EVD_MS2OverSampling def: 250
YAML: order$qcMetric_EVD_PreCal def: 260
YAML: order$qcMetric_EVD_PostCal def: 270
YAML: order$qcMetric_MSMS_MSMSDecal def: 280
YAML: order$qcMetric_SM_MSMSIdRate def: 300
YAML: order$qcMetric_MSMSScans_TopN def: 350 || new val: 120
YAML: order$qcMetric_MSMSScans_TopNID def: 380
YAML: order$qcMetric_MSMSScans_DepPep def: 383
YAML: order$qcMetric_EVD_MissingValues def: 390
YAML: order$qcMetric_EVD_PeptideCount def: 400
YAML: order$qcMetric_EVD_ProteinCount def: 450
YAML: order$qcMetric_AverageQualOverall def: 9999
Reading file D:\Programs\QCdir\QC-dragdrop\txt_folder/evidence.txt ...
Requiring column(s) 'retention.length' to be of type 'numeric'!
Requiring column(s) 'retention.time.calibration' to be of type 'numeric'!
Requiring column(s) 'retention.time', 'calibrated.retention.time' to be of type 'numeric'!
Requiring column(s) 'match.time.difference' to be of type 'numeric'!
Requiring column(s) 'intensity' to be of type 'numeric'!
Requiring column(s) 'mass.error..ppm.', 'mass.error..da.', 'uncalibrated.mass.error..ppm.', 'uncalibrated.mass.error..da.' to be of type 'numeric'!
Requiring column(s) 'uncalibrated...calibrated.m.z..ppm.', 'uncalibrated...calibrated.m.z..da.' to be of type 'numeric'!
Requiring column(s) 'm.z' to be of type 'numeric'!
Requiring column(s) 'score' to be of type 'numeric'!
WARNING: Could not find column regex '^fraction$' using case-INsensitive matching.
WARNING: Could not find column regex '[RK]\.Count' using case-INsensitive matching.
Requiring column(s) 'charge' to be of type 'numeric'!
Requiring column(s) 'mass' to be of type 'numeric'!
WARNING: Could not find column regex '^protein.names$' using case-INsensitive matching.
Requiring column(s) 'ms.ms.count' to be of type 'numeric'!
Requiring column(s) 'reporter.intensity.corrected.1', 'reporter.intensity.corrected.2', 'reporter.intensity.corrected.3', 'reporter.intensity.corrected.4', 'reporter.intensity.corrected.5', 'reporter.intensity.corrected.6', 'reporter.intensity.corrected.7', 'reporter.intensity.corrected.8', 'reporter.intensity.corrected.9', 'reporter.intensity.corrected.10', 'reporter.intensity.1', 'reporter.intensity.2', 'reporter.intensity.3', 'reporter.intensity.4', 'reporter.intensity.5', 'reporter.intensity.6', 'reporter.intensity.7', 'reporter.intensity.8', 'reporter.intensity.9', 'reporter.intensity.10', 'reporter.intensity.count.1', 'reporter.intensity.count.2', 'reporter.intensity.count.3', 'reporter.intensity.count.4', 'reporter.intensity.count.5', 'reporter.intensity.count.6', 'reporter.intensity.count.7', 'reporter.intensity.count.8', 'reporter.intensity.count.9', 'reporter.intensity.count.10' to be of type 'numeric'!
Keeping 47 of 92 columns!
Read 4778 entries from D:\Programs\QCdir\QC-dragdrop\txt_folder/evidence.txt.
Updating colnames
Simplifying contaminants
Simplifying reverse
Adding fc.raw.file column ... done
Starting to work on EVD:Contaminant (%s) ...

Memory [MB] prior|after|max(diff) : 65 | 66.5 | 71.3 (6)

Duration: 0 s

... EVD:Contaminant (%s)  done
Starting to work on EVD: Pep Intensity (">%1.1f") ...

Memory [MB] prior|after|max(diff) : 66.5 | 69.6 | 82 (16)

Duration: 0 s

... EVD: Pep Intensity (">%1.1f")  done
Starting to work on EVD: Reporter intensity ...
Error in data.table(df_reps) : 
 "data.table" function not found


I am not an R expert but seems like something is wrong with my R installation...

thanks again for your time... really appreciated...

cheers!

Mario

**Comment by mtinti** [comment]
Imarioernestovaldes ,
did you solved this issue?
I'm having the same problem with a TMT dataset. SILAC dataset and Label-free works fine for me....

**Comment by cbielow** [comment]
if you use PTXQC from within R, try `library(data.table)` before running any code related to PTXQC. If that does the trick, please let me know ... I have an idea what causes it...

**Comment by mtinti** [comment]
Hi, thanks for the suggestion!
Actually, after a bit of play around I just ended up to create a new R installation that solved the problem. Thumbs up for this package badly needed!!

**Comment by mtinti** [comment]
By the way... your suggestion is correct. Running library(data.table) before  PTXQC does solve the problem.

**Comment by FanqianYin** [comment]
Me too, meet same issue:
 
Error in data.table(df_reps) :
"data.table" function not found

And Running library(data.table) solved the problem.
