### ISSUE TITLE
Cannot make it run

### ISSUE THREAD

**Issue by kaniawave** [cbielow/PTXQC#71]
Hi!
I used the PTXQC previously without problems. Now on a new machine, somehow I am not able to make it run. Any ideas what did I do wrong this time? 

> This batch file is used to invoke the QC script by drag'n'dropping of
a MaxQuant txt folder (or any file within) onto this .bat file.
Within the same txt folder, a QC report in Html/PDF format will be created.

>First time installation of this script [for admins only]:
The script expects a certain structure to be present.
This .bat file expects a subfolder named '_internal'
which holds:
     'R-3.1.0'             Holds a complete R installation
                           (including all packages required to run the
                            PTXQC package)
     'compute_QC_report.R' The R script that is invoked by this .bat
Found QC directory at 'Z:\B_Rawfiles\Hek_Hela\QC-dragdrop\\_internal'
-- 'Z:\Witek\Projects\20191111-SCX_Marco\MQ-txt' is a directory
Txt folder is at 'Z:\Witek\Projects\20191111-SCX_Marco\MQ-txt'
Found R at '"Z:\B_Rawfiles\Hek_Hela\QC-dragdrop\\_internal"\R-3.1.0\bin\x64\rscr
ipt.exe'.
Using YAML  file and calling R now ...
Calling '"Z:\B_Rawfiles\Hek_Hela\QC-dragdrop\\_internal"\R-3.1.0\bin\x64\rscript
.exe --vanilla "Z:\B_Rawfiles\Hek_Hela\QC-dragdrop\\_internal"\compute_QC_report
.R Z:\Witek\Projects\20191111-SCX_Marco\MQ-txt '
Error: package or namespace load failed for 'PTXQC':
 .onLoad failed in loadNamespace() for 'pillar', details:
  call: utils::packageVersion("vctrs")
  error: there is no package called 'vctrs'
Execution halted
Failed folder Z:\Witek\Projects\20191111-SCX_Marco\MQ-txt. Does it exist and is
writeable!?

>The error should be indicated above.
Common errors are (yours might be different)
>  - your R installation runs out of memory; especially if its 32bit
>  - the file 'Z:\B_Rawfiles\Hek_Hela\QC-dragdrop\\_internal\compute_QC_report.R'
> is missing

>If the error persists, follow the
>instructions on https://github.com/cbielow/PTXQC
>in the section 'Bug reporting'.

>Leave this window open until the bug report is submitted

>You can copy the text from this window by
>  1) right-clicking here
>  2) choose 'Select all'
>  3) press the 'Enter' key
>  4) paste it somewhere (issue ticket, email)
>This ensures that all text is available to debug the problem.
>Thanks!
>Press any key to continue . . .`

**Comment by kaniawave** [comment]
The `vctrs` package is in the library folder.
The file `compute_QC_report.R` is there. 

I see that it does not load the `PTXQC` package somehow.

**Comment by cbielow** [comment]
the `vctrs` package is a dependency of a dependency (`dplyr` if I recall correctly).
Did you install a development version of these, by chance?
This post https://github.com/tidyverse/dplyr/issues/4367 describes a similar problem.
The solution there was to uninstall the broken packages and reinstall from CRAN (via `install.packages("...")`.
Just make sure you do it using the R-installation which the drag-n-drop.bat uses; in your case `"Z:\B_Rawfiles\Hek_Hela\QC-dragdrop\_internal"\R-3.1.0\`

If this does not solve the problem, you can try to copy the whole `Z:\B_Rawfiles\Hek_Hela\QC-dragdrop` folder from the other machine where its running correctly. That should also solve the problem.

Let me know if either of these helped. If not, we can think of something more clever to do :)

**Comment by kaniawave** [comment]
Okay, so the issue was a completely different one and I am not sure what it was. So the QC folder was in the network location and not locally on the PC. When I moved the QC folder to a desktop, it just started to run without any problems.
