### ISSUE TITLE
Pandoc document conversion failed with error 61

### ISSUE THREAD

**Issue by mikulasekkamil** [cbielow/PTXQC#75]
Dear PTXQC developers,

I have the issue with report generating by PTXQC. Here is a detail of problem

Pandoc document conversion failed with error 61.
![mstsc_pZAngP1oOy](https://user-images.githubusercontent.com/48439080/73917898-af49ee00-48c0-11ea-9a44-f66e3d83f049.png)

I already installed different R versions and the pandoc was installed as well.

Thanks for any suggestion!
Best 
Kamil Mikulasek

CEITEC 
Czechia

**Comment by cbielow** [comment]
Hi,
thanks for reporting this!
Starting with PTXQC 1.0, there are new metrics (UpSetR plots) which include a small graphic (from in the help section to aid in interpretation of the plot. This png is currently fetched directly from GitHub... which is problematic if you dont have an internet connection on the machine generating the report...

I will fix this with the upcoming release in a few days.

For the meantime: just disable the UpSetR metric in the YAML file (which gets generated right next to your .txt files or mzTab file), by setting its value to `-1`.

**Comment by mikulasekkamil** [comment]
Hi,
thanks for response.

Unfortunately I did not find any UpSetR metric in YAML file.  Here is the yaml for 1.0.1 version

PTXQC:
  UseLocalMQPar: yes
  NameLengthMax_num: 10.0
  OutputFormats:
  - html
  - plainPDF
  PlainPDF:
    AddPageNumbers: 'on'
File:
  Summary:
    IDRate:
      Thresh_bad_num: 20.0
      Thresh_great_num: 35.0
  ProteinGroups:
    RatioPlot:
      LabelIncThresh_num: 4.0
    IntensityThreshLog2_num: 25.0
  Evidence:
    ProteinCountThresh_num: 3500.0
    IntensityThreshLog2_num: 23.0
    PeptideCountThresh_num: 15000.0
    SpecialContaminants:
      cont_MYCO:
      - MYCOPLASMA
      - '1'
    MQpar_MatchingTimeWindow_num: 1.0
    MatchBetweenRuns_wA: auto
    MQpar_firstSearchTol_num: 20.0
    firstSearch_outOfCalWarnSD_num: 2.0
    MQpar_mainSearchTol_num: .na
  MsMsScans:
    IonInjectionThresh_num: 10.0
order:
  qcMetric_PAR: 1.0
  qcMetric_PG_PCA: 3.0
  qcMetric_EVD_Top5Cont: 10.0
  qcMetric_PG_Ratio: 19.0
  qcMetric_EVD_UserContaminant: 20.0
  qcMetric_SM_TIC: 25.0
  qcMetric_EVD_PeptideInt: 30.0
  qcMetric_EVD_ReporterInt: 31.0
  qcMetric_PG_RawInt: 32.0
  qcMetric_PG_LFQInt: 33.0
  qcMetric_PG_ReporterInt: 34.0
  qcMetric_MSMS_MissedCleavages: 40.0
  qcMetric_EVD_Charge: 100.0
  qcMetric_PG_Cont: 110.0
  qcMetric_MSMSScans_TopNoverRT: 120.0
  qcMetric_EVD_IDoverRT: 150.0
  qcMetric_EVD_RTPeakWidth: 170.0
  qcMetric_EVD_MBRAlign: 210.0
  qcMetric_EVD_MBRIdTransfer: 220.0
  qcMetric_EVD_MBRaux: 221.0
  qcMetric_MSMSScans_IonInjTime: 240.0
  qcMetric_MSMSScans_MSMSIntensity: 245.0
  qcMetric_EVD_MS2OverSampling: 250.0
  qcMetric_EVD_PreCal: 260.0
  qcMetric_EVD_PostCal: 270.0
  qcMetric_MSMS_MSMSDecal: 280.0
  qcMetric_SM_MSMSIdRate: 300.0
  qcMetric_MSMSScans_TopNID: 380.0
  qcMetric_MSMSScans_DepPep: 383.0
  qcMetric_EVD_MissingValues: 390.0
  qcMetric_EVD_PeptideCount: 400.0
  qcMetric_EVD_ProteinCount: 450.0
  **qcMetric_EVD_UpSet: 500.0** **only related to Upset metric which I found**
  qcMetric_AverageQualOverall: 9999.0

Is it any different option to fix them? 

Thanks
Kamil M.

**Comment by cbielow** [comment]
thats the one! :)
Set it to
`qcMetric_EVD_UpSet: -500.0`
and PTXQC will skip this metric.

**Comment by mikulasekkamil** [comment]
It works :) 
Thanks a lot!
