### ISSUE TITLE
Stuck in installation

### ISSUE THREAD

**Issue by reviewer3** [cbielow/PTXQC#9]
Hi,

I have issues installing the package. I am following the very helpful installation documentation and after installing PTXQC it returns 
```
The downloaded binary packages are in
        C:\Users\reviewer3\AppData\Local\Temp\RtmpwbY4zy\downloaded_packages
```

This folder does not contain '<libR>\PTXQC\inst\QC-dragdrop'. Is there anything I can do to get unstuck?

Btw with `(let's call it )` I guess you mean `(let's call it <QCdir>)`.

Thanks!

**Comment by cbielow** [comment]
The message you are referring to (`The downloaded binary package ...` should show up when either
`install.packages(...)`, `source("http://bioconductor.org/biocLite.R")` or `biocLite("Biobase")` are executed.
This however, happens **before** PTXQC is downloaded from github (via `install_github(...)`.
I've paste the output I get here https://gist.github.com/cbielow/03c1ec785901e812c16e.

The **last** line is the one which is interesting (starting with `Copy the packages contained in ..`).
If something went wrong during one of the intermediate commands, this line will not be printed.

I've updated the installation documentation to more explicitly state that each command should be run separately and also added a FAQ of common errors which occur with CRAN mirrors.

The new installation procedure now prints a slightly different last line, i.e. `PTXQC was installed to ...` which hopefully is a bit clearer.

> Btw with (let's call it ) I guess you mean (let's call it `<QCdir>`).

Whops. Corrected. Thanks!

**Comment by cbielow** [comment]
If the above does not help to resolve your problem, please paste the *complete* R console output you get here (or into a Gist like I did above). This should then enable a more detailed response.

**Comment by cbielow** [comment]
Did this work for you? I.e. can the issue be closed?

**Comment by reviewer3** [comment]
Sorry got busy since then, I'll test it again later today. Note that I was executing all commands the one after the other as detailed in the documentation. Will uninstall R and previous versions of the tool, hopefully it'll help.

Thanks for your quick answers.

**Comment by reviewer3** [comment]
Hi again,

The installation in R went fine after cleaning up my installation. Thanks for your help. Can it be that older versions of Bioconductor or PTXQC can impair the installation?

I am now on step 2 of the copy pasting. There is no ```<libR>\PTXQC\inst\QC-dragdrop``` but one ```<libR>\PTXQC\dragNdrop\QC-dragdrop```. Is that the one I am supposed to copy?

**Comment by reviewer3** [comment]
Seems like it. The installation went fine, I will try to get some projects through tomorrow. Thank you for your kind help!

**Comment by cbielow** [comment]
> The installation in R went fine after cleaning up my installation. Thanks for your help. Can it be that 
> older versions of Bioconductor or PTXQC can impair the installation?

Older versions of PTXQC will just be overwritten, but I'm not sure what Bioconductor is doing.
But glad to see it worked.

**Comment by cbielow** [comment]
I'll close this ticket. If you have questions when running PTXQC, just open a new ticket.

**Comment by reviewer3** [comment]
Great, I will come back to you if we encounter more issues in our lab. Everything worked out perfectly fine with this version, thanks to your help. PTXQC will surely be very helpful to proteomic labs, it answers a very important need for us, and we will use it routinely from now on. Thank you very much, and congratulations for this very nice piece of work
