### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fabianegli** [cbielow/PTXQC#92]
While the README and the PTXQC developers/maintainer encourage community contributions, the license does not. I strongly suggest to change to a more permissive license.

Some immediate thoughts:

* Contributors can not be certain that their contributions remain accessible to the general public.
* Contributors open themselves to legal trouble by copying the work. This unfortunately includes forking and using the code.
* Contributors can not be certain that their code creations can not be pulled from the public against their will.

The applicability of the current license to code originating from pull requests of contributors from outside the "PTXQC Team" is questionable at best.

I like PTXQC but would like it even more if it were released under a GPLv3, MIT or similar license.

**Comment by fabianegli** [comment]
https://opensource.guide/legal/, https://www.fsf.org/licensing/ and https://www.gnu.org/licenses/license-recommendations.html  are valuable resources, not only to developers choosing a license but also as a resource of convincing arguments that can be sway the opinion of legal teams involved that have to greenlight the use of a permissive license.

**Comment by cbielow** [comment]
I've added a small paragraph to the `readme.md` to make the license very explicit. Hope that helps.

**Comment by fabianegli** [comment]
Thank you for the update and continuing to educate me on R-package development quirks. I do not intend to change R at all. 

Maybe GitHub could/should display the licensing information in R-package repositories better by default.

Another option for you could be to add a licensing badge at the top of the README. That would look like so:

[![License](https://img.shields.io/badge/License-BSD%203--Clause-blue.svg)](https://opensource.org/licenses/BSD-3-Clause)

Since the note made it into the README I think this issue is sufficiently served to be closed.

**Comment by cbielow** [comment]
Good point. I've added the badge as well. 
Closing issue.
