### ISSUE TITLE
PTXQC issue: hangs when Creating Report file

### ISSUE THREAD

**Issue by Alxcho** [cbielow/PTXQC#93]
Hi, for some reason createReport hangs shortly after Creating Report file on local MaxQuant output and never completes. Using the example dataset from PRIDE all works fine. When using local MaxQuant output however, PTXQC proceeds seemingly fine until it doesn't. Last console shows as follow:

[...]
Creating Report file ...HTML TEMPLATE: C:/Users/XXX_XXX/Documents/R/win-library/4.0/PTXQC/./reportTemplate/PTXQC_report_template.Rmd

processing file: PTXQC_report_template.Rmd
  |............                                                                                            |  11%
  ordinary text without R code

  |.......................                                                                                 |  22%
label: setup (with options) 
List of 1
 $ include: logi FALSE

  |...................................                                                                     |  33%
   inline R code fragments

  |..............................................                                                          |  44%
label: MQparams (with options) 
List of 2
 $ echo   : logi FALSE
 $ results: chr "asis"

  |..........................................................                                              |  56%
  ordinary text without R code

  |.....................................................................                                   |  67%
label: nameMapping (with options) 
List of 2
 $ echo   : logi FALSE
 $ results: chr "asis"

  |.................................................................................                       |  78%
  ordinary text without R code

  |............................................................................................            |  89%
label: metrics (with options) 
List of 2
 $ echo   : logi FALSE
 $ results: chr "asis"

Thanks,
Alex

**Comment by cbielow** [comment]
Hi Alex,

The problem could be anything from hardware (how much RAM does your machine have, and how big is the dataset?), to software (do you use a 32-bit version of R? or maybe its a buggy pandoc...). Hard to tell.
Do you see CPU/hard drive activity in the Windows Task Manager when there is seemingly no output?
To sum up, this is hard to diagnose. You can try to send me the input data, so we can exclude it as the culprit. Could you upload it somewhere?

**Comment by Alxcho** [comment]
Hi, thanks for the answer. Currently doing some more tests to confirm but it seems it was indeed a hardware issue. The report actually completed after a few attempts, the solution was just to leave it running for 26 min. Other reports using other datasets completed much faster, not quite sure what was the matter with that one (CPU / hard drive activity was definitely high from MQ running at the same time, but nothing really extraordinary - 50% of the 32Gb ram was used then, dataset was 35Gb). Anyway, problem solved! Thanks.

**Comment by cbielow** [comment]
nice.
Thanks for the info.
