### ISSUE TITLE
Error with pandoc 2.12

### ISSUE THREAD

**Issue by jpfeuffer** [cbielow/PTXQC#95]
```
  pandoc: (TagClose "script") is not a TagOpen
  CallStack (from HasCallStack):
    error, called at src/Text/HTML/TagSoup/Type.hs:128:19 in tagsoup-0.14.8-5475800661a147b74c5702e44e2bf7ad3c7dd7de6abc3374f8bae019636b95cb:Text.HTML.TagSoup.Type
  Error: pandoc document conversion failed with error 1
  In addition: There were 19 warnings (use warnings() to see them)
  Execution halted
```

From:  https://github.com/nf-core/proteomicslfq/pull/122/checks?check_run_id=2065895445
MzTab: https://gist.github.com/jpfeuffer/4dd842c09836d9718a3b40b911952a3f
With the default template.
Everything from conda.

I assume it is a regression in pandoc or an incompatibility of the new version with RMarkdown.

**Comment by jpfeuffer** [comment]
We had to downgrade pandoc.

**Comment by Alxcho** [comment]
Same, downgrading from pandoc 2.13 solved the issue.
